import random
from reference_data import Country

type = (
    ("USA", "Insurance"),
    ("USA", "Insurance Company"),
    ("USA", "Insurance Society"),
    ("USA", "Mutual"),
    ("USA", "Mutual Insurers"),
    ("USA", "Assurance Co."),
    ("USA", "Insurance Group"),
    ("USA", "Insurance Department"),
    ("USA", "Union"),
    ("USA", "Mutual Group"),
    ("USA", "Capital"),
    ("ITA", "Assicurazioni"),
    ("ITA", "Gruppo Mutualistico"),
    ("ITA", "Gruppo Assicurativo"),
    ("FRA", "Assurance"),
    ("FRA", "Assureurs"),
    ("FRA", "Groupe Mutuel"),
    ("BRA", "Seguros"),
    ("BRA", "Grupo Mútuo"),
    ("BRA", "União"),
    ("BRA", "Seguradoras"),
    ("ESP", "Seguros"),
    ("ESP", "Aseguradoras"),
    ("GER", "Versicherung"),
    ("GER", "Versicherer"),
    ("GER", "Assicurazioni"),
    ("SWE", "Försäkringar"),
    ("SWE", "Försäkring"),
    ("SWE", "Försäkringsbolag"),
)
single_name = (
    "Insuritas",
    "Assurelines",
    "Insuricare",
    "Umbrellife",
    "Assuricare",
    "Mutualmotor",
    "Brolife",
    "Gercare",
    "Brassurance",
)


def test_insurance_data_generator(nr: int, countries: list[Country]) -> list[tuple[str, str, str]]:
    if nr > 700:
        ValueError("max 700 companies")
    if any(
        company[0] not in [c.iso_code_3 for c in countries] for company in companies
    ):
        ValueError("The given list of countries is lacking some needed values")
    values_per_country = nr // 7
    total_list = []
    for country in countries:
        single_country_values = [
            company for company in companies if company[0] == country.iso_code_3
        ]
        total_list.extend(single_country_values[:values_per_country])
    for v in total_list:
        v[1] += " " + random.choice([t[1] for t in type if t[0] == v[0]])
    for i in range(nr - values_per_country * 7):
        total_list.append(
            ("USA", single_name[i], f"{single_name[i].lower()}@email.com")
        )
    return total_list


companies = (
    ["USA", "Morissette, Koepp and Bartoletti", "jo14@gusikowski.com"],
    ["USA", "Bergnaum, Lockman and Huel", "grant.stracke@gislason.com"],
    ["USA", "Fay", "chet72@bahringer.com"],
    ["USA", "King", "nya03@rosenbaum.com"],
    ["USA", "Kohler", "zhoeger@stehr.info"],
    ["USA", "Mills", "waters.harry@walker.com"],
    ["USA", "Boyle", "reilly.maiya@crist.net"],
    ["USA", "Price", "shaniya47@schumm.com"],
    ["USA", "Marks, Huels and Bergnaum", "marie53@aufderhar.com"],
    ["USA", "Frami, Bins and Rice", "cathryn98@mitchell.com"],
    ["USA", "Rice", "marguerite45@lesch.info"],
    ["USA", "Stracke", "klarson@graham.info"],
    ["USA", "Upton", "ymedhurst@treutel.org"],
    ["USA", "Vandervort", "richie.considine@morissette.com"],
    ["USA", "Watsica-Bradtke", "yfay@eichmann.com"],
    ["USA", "McCullough-Hintz", "fahey.adelle@mante.info"],
    ["USA", "Bahringer", "adrain16@schimmel.biz"],
    ["USA", "Harris", "wilson98@brakus.org"],
    ["USA", "Murphy", "marcia.gutkowski@dickinson.com"],
    ["USA", "Gerhold", "oroob@grady.net"],
    ["USA", "Romaguera, Jakubowski and Wilkinson", "carlotta48@windler.com"],
    ["USA", "Rau, Hamill and McCullough", "stewart.armstrong@heller.org"],
    ["USA", "Emard, Will and Legros", "ykonopelski@yundt.com"],
    ["USA", "Mueller-Bernier", "caitlyn.botsford@homenick.com"],
    ["USA", "Hegmann", "waino.balistreri@wolff.com"],
    ["USA", "Lang", "jacey.yost@brakus.com"],
    ["USA", "Cartwright, Weimann and Rempel", "shane.welch@gislason.com"],
    ["USA", "Pfeffer", "gmurazik@greenholt.com"],
    ["USA", "Schiller, Adams and Dickinson", "rschmeler@legros.biz"],
    ["USA", "Hamill and Sons", "graciela.kertzmann@cummerata.com"],
    ["USA", "Pouros, Ryan and Simonis", "rmohr@lockman.com"],
    ["USA", "Kling, Tromp and Schmidt", "jenifer.ratke@feeney.com"],
    ["USA", "Ledner, Abbott and Haag", "gtremblay@kuhic.org"],
    ["USA", "Schamberger", "olindgren@oconnell.biz"],
    ["USA", "Kohler-Littel", "mark45@powlowski.com"],
    ["USA", "Heaney-Daugherty", "halie.boehm@schowalter.com"],
    ["USA", "Schinner-Schiller", "hand.dewitt@glover.com"],
    ["USA", "Willms-Orn", "mraz.aurore@olson.org"],
    ["USA", "Durgan, Orn and Lueilwitz", "urogahn@streich.com"],
    ["USA", "Grimes, Hessel and Zemlak", "schuppe.nicole@wiegand.com"],
    ["USA", "McCullough", "ivory.runolfsson@oberbrunner.com"],
    ["USA", "Kozey, Terry and Bradtke", "jdare@streich.com"],
    ["USA", "Muller, Leuschke and Okuneva", "abshire.daren@thompson.org"],
    ["USA", "Hyatt, Hill and Hills", "rrodriguez@parisian.com"],
    ["USA", "Ward", "harber.sadie@corwin.org"],
    ["USA", "Bogan-Berge", "zachery88@breitenberg.biz"],
    ["USA", "Yundt, Windler and Fisher", "katlyn18@simonis.com"],
    ["USA", "Reilly-Legros", "kieran08@jerde.com"],
    ["USA", "Bernier", "rhea.goyette@runolfsdottir.com"],
    ["USA", "Lesch-Brekke", "richie.pfeffer@wyman.com"],
    ["USA", "Leffler, Dietrich and Hodkiewicz", "cathy64@thiel.com"],
    ["USA", "Bartell-Maggio", "bemard@dietrich.com"],
    ["USA", "Larkin, Wehner and Murazik", "madie34@rau.com"],
    ["USA", "Torphy", "gdonnelly@volkman.com"],
    ["USA", "Dicki, Price and Torphy", "bwintheiser@batz.info"],
    ["USA", "Marvin", "dortha.schmeler@jacobson.com"],
    ["USA", "Robel, Howell and Anderson", "pouros.erik@swift.net"],
    ["USA", "Schroeder", "akohler@hermiston.com"],
    ["USA", "Bernier", "rau.carolyne@haley.net"],
    ["USA", "Ondricka", "holden.lubowitz@tromp.com"],
    ["USA", "Schmeler-Yundt", "xbeatty@kirlin.com"],
    ["USA", "Moen-Brown", "homenick.mauricio@lakin.org"],
    ["USA", "Ryan, Ondricka and Prosacco", "harrison.johnson@sanford.com"],
    ["USA", "Greenfelder, Olson and Crona", "kris.ena@hahn.com"],
    ["USA", "O'Reilly", "weissnat.lloyd@daugherty.com"],
    ["USA", "Ruecker Inc", "weissnat.hubert@bernhard.net"],
    ["USA", "Witting and Sons", "aniyah.gorczany@kiehn.com"],
    ["USA", "Hansen", "maynard26@upton.com"],
    ["USA", "Collins-Heaney", "neha18@schneider.com"],
    ["USA", "Mayert-Johnston", "zboyle@schmeler.com"],
    ["USA", "Schmidt", "omari.crona@mcdermott.org"],
    ["USA", "Weimann-Purdy", "bstreich@fahey.com"],
    ["USA", "Harvey-Gusikowski", "dmueller@torphy.com"],
    ["USA", "Jast and Sons", "brice77@reinger.com"],
    ["USA", "McGlynn, O'Connell and Stiedemann", "dlabadie@gleason.com"],
    ["USA", "Conroy", "barton.alexanne@langosh.com"],
    ["USA", "Ruecker, Johns and Flatley", "walsh.viva@greenfelder.com"],
    ["USA", "Fahey", "kian.ritchie@metz.com"],
    ["USA", "Abernathy-Hickle", "myrtice.pfannerstill@kohler.com"],
    ["USA", "O'Kon", "ara65@oconner.com"],
    ["USA", "Leuschke-Miller", "oschiller@bailey.net"],
    ["USA", "Christiansen-Tremblay", "rath.hertha@kautzer.com"],
    ["USA", "Volkman", "steuber.sister@hammes.biz"],
    ["USA", "Nicolas", "kunze.winifred@marquardt.com"],
    ["USA", "Davis, Emard and Hoeger", "idell68@considine.com"],
    ["USA", "Haag, Friesen and Hansen", "smith.cassie@hermiston.com"],
    ["USA", "Kunde", "jenkins.marina@kohler.com"],
    ["USA", "Kiehn-Zboncak", "aherzog@boyer.com"],
    ["USA", "Heller and Sons", "thiel.norris@weber.com"],
    ["USA", "Kertzmann, Kerluke and Wisoky", "mkilback@reinger.net"],
    ["USA", "Heaney, McKenzie and Hamill", "karson.bogan@homenick.net"],
    ["USA", "Lockman-Runolfsson", "grady.estel@stokes.com"],
    ["USA", "Howell-Towne", "kcollier@harris.com"],
    ["USA", "Heidenreich Inc", "darrion03@mckenzie.info"],
    ["USA", "O'Conner", "lexi.homenick@kohler.net"],
    ["USA", "Zboncak", "schamberger.alberta@gottlieb.biz"],
    ["USA", "Deckow-Renner", "dorothea91@macejkovic.org"],
    ["USA", "Larson, Monahan and Abernathy", "landen40@bruen.com"],
    ["USA", "Heidenreich-Kemmer", "ciara40@king.org"],
    ["USA", "Parker Inc", "trisha.ledner@luettgen.com"],
    ["ITA", "Fontana-Sartori", "benedetti.lia@sartori.com"],
    ["ITA", "Fontana, Russo e Negri e figli", "samira51@ricci.net"],
    ["ITA", "Amato, Bianchi e Fabbri", "eufemia.bruno@rossi.com"],
    ["ITA", "Conte", "negri.baldassarre@russo.it"],
    ["ITA", "De Luca", "gianantonio.ferri@russo.com"],
    ["ITA", "Damico e figli", "ldeangelis@bianchi.com"],
    ["ITA", "Bianchi", "akira42@greco.com"],
    ["ITA", "Pellegrino-Vitale e figli", "miriam.testa@sanna.it"],
    ["ITA", "Damico-Conti", "lamato@pellegrino.com"],
    ["ITA", "Vitali e figli", "giordano.pellegrini@bernardi.org"],
    ["ITA", "Villa-Coppola e figli", "ktesta@vitali.it"],
    ["ITA", "Vitali", "wtesta@testa.com"],
    ["ITA", "Marino", "sala.sandro@marchetti.org"],
    ["ITA", "Leone, Palumbo e Palmieri", "svitali@orlando.com"],
    ["ITA", "Bianchi", "marino.rosolino@piras.net"],
    ["ITA", "Monti e figli", "mietta44@ferretti.it"],
    ["ITA", "Mazza, D'amico e Damico e figli", "mercedes17@desantis.it"],
    ["ITA", "D'amico, Fiore e Ferraro", "galli.filomena@rinaldi.it"],
    ["ITA", "Orlando-Milani", "longo.modesto@mariani.com"],
    ["ITA", "Villa-Donati", "mirko.silvestri@costa.it"],
    ["ITA", "Palmieri", "elga10@lombardi.net"],
    ["ITA", "Sartori, Pagano e Marino e figli", "tolomeo.mariani@marini.com"],
    ["ITA", "De luca, Martini e Martinelli", "ffarina@monti.com"],
    ["ITA", "Barbieri, Guerra e Testa", "mirco92@pellegrino.it"],
    ["ITA", "Damico e figli", "silverio53@bruno.com"],
    ["ITA", "Gentile-Grasso e figli", "damico.rosolino@serra.net"],
    ["ITA", "Barbieri", "sueellen75@riva.org"],
    ["ITA", "Ferri-Fiore", "martino.fulvio@esposito.com"],
    ["ITA", "Rossetti-Mancini", "vlongo@sala.com"],
    ["ITA", "Bruno", "santo.battaglia@colombo.it"],
    ["ITA", "Riva, Fiore e De rosa e figli", "sirio17@rossetti.com"],
    ["ITA", "Mazza-Sorrentino", "neri.rossetti@santoro.it"],
    ["ITA", "Esposito-Bernardi", "bmonti@sanna.net"],
    ["ITA", "Coppola", "ypalmieri@monti.net"],
    ["ITA", "De rosa, Orlando e Coppola e figli", "caruso.luce@bianchi.net"],
    ["ITA", "Giordano-Riva", "damico.osea@parisi.com"],
    ["ITA", "Pagano", "marino.alighieri@lombardo.it"],
    ["ITA", "Morelli-Pellegrino", "wcarbone@valentini.org"],
    ["ITA", "Barbieri-Palmieri", "caligola90@mazza.it"],
    ["ITA", "Vitali", "sartori.battista@martino.it"],
    ["ITA", "Vitali, Palumbo e Parisi", "colombo.loretta@battaglia.com"],
    ["ITA", "Basile", "mauro61@messina.com"],
    ["ITA", "Vitale-Mancini e figli", "samuel30@esposito.it"],
    ["ITA", "Coppola", "leone.leone@martini.com"],
    ["ITA", "D'angelo, Neri e Romano e figli", "villa.sibilla@coppola.com"],
    ["ITA", "Caruso e figli", "jpiras@valentini.it"],
    ["ITA", "Giuliani e figli", "mauro.fontana@carbone.org"],
    ["ITA", "Mariani", "elda.testa@farina.net"],
    ["ITA", "Fontana-Martinelli", "esposito.gerlando@orlando.net"],
    ["ITA", "D'angelo", "walter.martino@esposito.com"],
    ["ITA", "Ferraro-Guerra e figli", "piererminio.amato@giuliani.org"],
    ["ITA", "Sanna, Mancini e Piras e figli", "rizzi.pietro@messina.it"],
    ["ITA", "De Santis, Mariani e Conti e figli", "conti.joseph@lombardo.net"],
    ["ITA", "Ferraro", "cassiopea88@conte.it"],
    ["ITA", "Fabbri-Ferraro", "ilario.negri@vitali.net"],
    ["ITA", "Gentile, Fontana e Negri", "bgiuliani@gallo.com"],
    ["ITA", "Sanna", "miriam.benedetti@mariani.org"],
    ["ITA", "D'angelo", "tolomeo.giordano@deluca.com"],
    ["ITA", "Colombo, Esposito e Palumbo e figli", "gcosta@barone.it"],
    ["ITA", "Pellegrino, Barbieri e Bianco", "vitale.timoteo@mancini.com"],
    ["ITA", "Rizzo, Morelli e Rizzo", "csala@sartori.com"],
    ["ITA", "Testa, Ferretti e Colombo", "dimitri.fabbri@messina.it"],
    ["ITA", "Coppola-Santoro", "mancini.michele@martino.org"],
    ["ITA", "Sartori", "erminia02@gatti.org"],
    ["ITA", "Giuliani, Amato e Esposito", "jleone@morelli.com"],
    ["ITA", "Rizzo-Milani e figli", "romano.fiorenzo@desantis.com"],
    ["ITA", "Donati, Greco e Marini", "anastasio.rizzo@barone.it"],
    ["ITA", "Conte, Basile e Romano", "fortunata.marini@piras.net"],
    ["ITA", "Ruggiero", "pbarone@esposito.com"],
    ["ITA", "Ricci", "dmarini@martinelli.com"],
    ["ITA", "Milani, Testa e Milani", "nconte@martini.it"],
    ["ITA", "Conte, Martinelli e Mancini", "bianchi.jelena@mariani.org"],
    ["ITA", "Leone", "rizzo.assia@gatti.com"],
    ["ITA", "Martino e figli", "caruso.matilde@ferretti.org"],
    ["ITA", "Longo-Mazza", "qmartini@bernardi.it"],
    ["ITA", "Messina", "hcaruso@rizzo.net"],
    ["ITA", "Barbieri-Rossetti e figli", "fiorentino91@galli.com"],
    ["ITA", "Cattaneo e figli", "neri.bortolo@deangelis.com"],
    ["ITA", "Benedetti-Farina", "rparisi@marino.com"],
    ["ITA", "Fiore-Caruso", "mancini.edvige@barbieri.net"],
    ["ITA", "Testa, Palmieri e De rosa", "coppola.edilio@leone.com"],
    ["ITA", "Colombo", "jconte@ruggiero.it"],
    ["ITA", "Giuliani e figli", "orfeo.sartori@bernardi.it"],
    ["ITA", "Martino", "sartori.mietta@villa.com"],
    ["ITA", "Testa", "xdangelo@bianchi.com"],
    ["ITA", "Ferretti-Sanna e figli", "olongo@ferraro.net"],
    ["ITA", "Carbone, Pellegrino e Martino", "matteo67@vitali.it"],
    ["ITA", "Neri", "rvilla@romano.it"],
    ["ITA", "Battaglia-Lombardo e figli", "ingrid.damico@bellini.com"],
    ["ITA", "Amato", "benedetti.damiana@sorrentino.com"],
    ["ITA", "Ruggiero-Morelli e figli", "carmela.conte@dangelo.org"],
    ["ITA", "Villa", "flaviana.pellegrino@amato.net"],
    ["ITA", "Pellegrini, Serra e Farina e figli", "imessina@romano.org"],
    ["ITA", "Santoro, Gentile e Gentile", "ofontana@giordano.com"],
    ["ITA", "Palmieri, Cattaneo e Milani", "vfarina@barone.it"],
    ["ITA", "Farina, Damico e Piras", "ferri.cesidia@bellini.it"],
    ["ITA", "Sanna-Silvestri e figli", "nguerra@pagano.com"],
    ["ITA", "Bernardi-Palmieri", "manuele.bianchi@marchetti.com"],
    ["ITA", "Rinaldi, Neri e Morelli", "elda00@caputo.it"],
    ["ITA", "Caputo-Fabbri", "mirco20@basile.com"],
    ["ESP", "Banda y Jaimes y Asoc.", "ros.pedro@conde.es"],
    ["ESP", "Jimínez y Alejandro e Hijos", "gracia.cesar@munguia.org"],
    ["ESP", "Almanza de Heredia e Hijo", "zmillan@carrasquillo.com"],
    ["ESP", "Zarate-Esparza", "ogriego@delarosa.com"],
    ["ESP", "Grupo Escudero-Rodrigo", "luis.bermudez@montez.com"],
    ["ESP", "Pastor-Llorente y Flia.", "cesar49@amador.com"],
    ["ESP", "Delao de Saavedra", "rodrigo23@ocampo.com"],
    ["ESP", "Gestora Murillo", "africa.garica@samaniego.com"],
    ["ESP", "Nieto-Gaona", "villar.lola@perales.es"],
    ["ESP", "Anguiano, Juan y Quiñones", "omar91@cazares.net"],
    ["ESP", "Del Río y Valdés", "malak57@murillo.es"],
    ["ESP", "Tafoya y Cervantes e Hija", "godoy.adriana@serra.es"],
    ["ESP", "Cabrera de Salcedo", "david.mota@aponte.com.es"],
    ["ESP", "Rincón de Pastor", "ymuro@gonzalez.net"],
    ["ESP", "Valladares, Aranda y Marco", "andres.mercado@rincon.com"],
    ["ESP", "Tamayo de Madrigal", "carlos.rodriquez@ozuna.com"],
    ["ESP", "Centro Quiñónez-Mercado", "villarreal.helena@elizondo.com"],
    ["ESP", "Centro Cruz", "ebarreto@diaz.org"],
    ["ESP", "Quintero y Yáñez", "david.negrete@otero.org"],
    ["ESP", "Cuesta-Solano", "tcortes@garza.es"],
    ["ESP", "Colón-Colunga", "xbarela@corona.org"],
    ["ESP", "Barela, Gaytán y Bermejo e Hijo", "jvera@ceja.net"],
    ["ESP", "Rojas-Rolón e Hijo", "lamador@corona.com"],
    ["ESP", "Serrato y Archuleta y Flia.", "zbrito@vanegas.net"],
    ["ESP", "Bañuelos-Macias", "pena.rafael@benavidez.es"],
    ["ESP", "Atencio de Tejeda e Hijo", "vanegas.patricia@nunez.es"],
    ["ESP", "Asociación Reyes-Gimeno", "preciado.alejandra@cepeda.org"],
    ["ESP", "Velasco y Reynoso", "raul89@urena.com"],
    ["ESP", "Villareal, De la Torre y Valdez", "paula.lerma@torres.org"],
    ["ESP", "Alaniz de Alarcón", "escobedo.martina@jaime.com"],
    ["ESP", "Camacho y Cortés y Asoc.", "alex29@sanchez.es"],
    ["ESP", "Grupo Preciado", "rafael.sosa@caldera.es"],
    ["ESP", "Asociación Saucedo e Hijo", "sdomingo@menchaca.es"],
    ["ESP", "Andrés y Álvarez", "cristina.lara@rojo.com"],
    ["ESP", "Corporación Bahena-Moral", "nuribe@aparicio.com"],
    ["ESP", "Centro Fonseca-Páez", "segura.alba@ochoa.es"],
    ["ESP", "Centro Rodarte-Delagarza", "dcantu@armenta.es"],
    ["ESP", "Sierra de Chacón e Hijos", "mar.matos@vera.com"],
    ["ESP", "Rivero de Barragán", "oliver95@aguayo.es"],
    ["ESP", "Grupo Guillen", "erodriguez@sancho.net"],
    ["ESP", "Lorenzo-Razo", "ana.becerra@rivas.org"],
    ["ESP", "Oquendo de Mendoza", "cesar.mesa@benavides.com"],
    ["ESP", "Leyva y Guardado", "resendez.andrea@delapaz.com"],
    ["ESP", "Girón y Batista", "antonio.melendez@salazar.com"],
    ["ESP", "Puente de Font e Hijo", "oscar.caro@tejeda.com"],
    ["ESP", "Pereira de Batista", "rosa.nicolas@gallardo.es"],
    ["ESP", "Munguía de Garibay y Asoc.", "adriana.jurado@casas.com"],
    ["ESP", "Guevara y Tejada", "zorosco@flores.com"],
    ["ESP", "Global Ulloa", "hmunguia@apodaca.com"],
    ["ESP", "Rocha de Domínguez e Hijos", "lazaro.juanjose@casillas.com"],
    ["ESP", "Gestora Osorio-Covarrubias", "bpatino@solorio.net"],
    ["ESP", "Gestora Garica", "velasco.sandra@toledo.es"],
    ["ESP", "Carrión de Galán e Hijo", "david.quintana@romo.es"],
    ["ESP", "Benavídez-Pozo y Flia.", "ariadna59@hinojosa.es"],
    ["ESP", "Cantú y Casárez", "aroa.ulloa@marquez.org"],
    ["ESP", "Ulloa y Corona", "iria88@fierro.com"],
    ["ESP", "Air Rascón-Lucas", "izan62@rincon.es"],
    ["ESP", "Ornelas-Ruelas e Hija", "vizquierdo@navarrete.es"],
    ["ESP", "Anguiano de Navarro e Hijos", "qpuga@arriaga.com"],
    ["ESP", "Centro Patiño", "valadez.vera@armas.es"],
    ["ESP", "Centro Gimeno-Bahena", "rico.pedro@urrutia.es"],
    ["ESP", "Arriaga-Chávez", "ivan.aleman@roig.com"],
    ["ESP", "Ramírez-Moreno", "ainara.alonzo@arreola.com"],
    ["ESP", "Espinoza de Benito", "franciscojavier.quintero@lugo.net"],
    ["ESP", "Izquierdo de Baeza", "gabriel.olivera@aguilar.net"],
    ["ESP", "Garica y Ulloa", "daniela78@ojeda.org"],
    ["ESP", "Soliz-Banda", "bruno.ybarra@saenz.org"],
    ["ESP", "Salcedo, Caldera y Martín", "silvia.barreto@mejia.com.es"],
    ["ESP", "Rosales-Centeno y Flia.", "rrueda@rosario.es"],
    ["ESP", "Asociación Bahena-Bahena", "hsepulveda@pizarro.net"],
    ["ESP", "Centro Abreu-Villalba", "yalaniz@puga.com"],
    ["ESP", "Viajes Ávila", "beatriz56@vallejo.es"],
    ["ESP", "Roque y Villalba y Asoc.", "frobledo@castellano.com"],
    ["ESP", "Corporación Cabán", "ian52@cuesta.com"],
    ["ESP", "Ornelas-Trejo", "zgarza@galan.es"],
    ["ESP", "Asociación Carbonell e Hijos", "qmatos@rosales.com"],
    ["ESP", "Parra y Melgar", "ledesma.pol@guardado.org"],
    ["ESP", "Viajes Briseño-Soria", "aaron.pizarro@rocha.es"],
    ["ESP", "Archuleta-Fajardo", "paola.delafuente@barrientos.com.es"],
    ["ESP", "Asociación Peralta", "abril62@riera.com"],
    ["ESP", "Betancourt, Olivo y Soler y Asoc.", "josemanuel.segovia@atencio.es"],
    ["ESP", "Pardo de Serrano e Hijos", "aquinones@pulido.com"],
    ["ESP", "Viajes Ledesma-Rendón", "teresa07@leal.es"],
    ["ESP", "Air Adame e Hijos", "yeray.abeyta@puig.com"],
    ["ESP", "Global Mateo", "ane.curiel@martinez.com"],
    ["ESP", "Armas de Crespo e Hija", "sergio85@irizarry.net"],
    ["ESP", "Soliz y Trejo y Asoc.", "izan.villalba@santiago.com"],
    ["ESP", "Nájera-Garza e Hijo", "alvaro.narvaez@razo.es"],
    ["ESP", "Asociación Aguirre e Hija", "ornelas.teresa@peres.com"],
    ["ESP", "Arriaga y Alfonso", "aaron10@farias.com"],
    ["ESP", "Ledesma-Tórrez", "coronado.oriol@monroy.com"],
    ["ESP", "Sanz de Carreón", "ian.prado@soliz.org"],
    ["ESP", "Centro Montemayor-Macías", "unai73@delafuente.com"],
    ["ESP", "Sisneros, Carrillo y Patiño", "flores.lucas@armijo.com.es"],
    ["ESP", "Camarillo, Robles y Vila", "paola33@delagarza.net"],
    ["ESP", "Carrasquillo y Zaragoza", "xaviles@elizondo.es"],
    ["ESP", "Alvarado de Montes", "pina.helena@aragon.com"],
    ["ESP", "Garibay-Cuesta", "adame.ismael@delacruz.com"],
    ["ESP", "Escobedo de Pérez", "marti05@anguiano.com"],
    ["ESP", "Grupo López-Riera", "marti24@fierro.org"],
    ["GER", "Beckmann", "josef73@brinkmann.com"],
    ["GER", "Noack", "lohmann.antonia@horn.de"],
    ["GER", "Frank", "koster.lidia@seidel.com"],
    ["GER", "Wolter Busse", "wendelin67@schulz.com"],
    ["GER", "Schindler", "greiner.sina@peter.net"],
    ["GER", "Frey Neubert & Co.", "qvoss@kretschmer.com"],
    ["GER", "Henkel", "bischoff.giesela@kuhn.com"],
    ["GER", "Harms", "adrian74@pietsch.com"],
    ["GER", "Weigel Bode & Co.", "kopp.corina@giese.net"],
    ["GER", "Knoll", "stadler.adrian@jurgens.de"],
    ["GER", "Rau", "wbertram@thiele.de"],
    ["GER", "Rothe", "jmartin@betz.com"],
    ["GER", "Bühler", "soren69@stumpf.com"],
    ["GER", "Kühne Lenz & Co.", "grausch@weis.com"],
    ["GER", "Naumann Heller", "magda.schulze@heim.com"],
    ["GER", "Michel Weiss", "ralf81@fuhrmann.com"],
    ["GER", "Thiele", "irma24@vogt.org"],
    ["GER", "Schuler & Co.", "witt.ingrid@beck.net"],
    ["GER", "Dietz", "mkroger@reinhardt.net"],
    ["GER", "Maier Schumacher e.V.", "schluter.josefine@reinhardt.com"],
    ["GER", "Stoll Thiel & Co.", "alinke@naumann.de"],
    ["GER", "Maurer Forster & Co.", "yvonne36@scherer.com"],
    ["GER", "Dietrich", "ortwin.nickel@kunze.com"],
    ["GER", "Horn Knoll", "edmund.heil@wunderlich.com"],
    ["GER", "25", "Keßler Rau", "heinemann.silvio@anders.de"],
    ["GER", "Mayer", "margaretha98@beer.de"],
    ["GER", "Ahrens", "lang.gerlinde@schneider.com"],
    ["GER", "Baur", "kiefer.ricarda@thomas.com"],
    ["GER", "29", "Heß & Co.", "plohmann@merkel.org"],
    ["GER", "Braun Stiftung & Co.", "marion.eckert@sonntag.de"],
    ["GER", "Strobel Heinze", "silvio.meyer@heil.com"],
    ["GER", "Ebert", "henri.adam@winter.org"],
    ["GER", "Schenk", "stephan.breuer@pape.net"],
    ["GER", "Gross", "kretschmer.manuela@scheffler.org"],
    ["GER", "Bergmann", "wfunk@dietz.de"],
    ["GER", "Witte", "ulrike24@fricke.com"],
    ["GER", "Schlegel", "grete.steffen@heine.de"],
    ["GER", "Röder", "pieper.heinzjosef@vogel.org"],
    ["GER", "Neubauer", "ute.weiss@gebhardt.net"],
    ["GER", "Stoll", "neubauer.maja@neuhaus.de"],
    ["GER", "Glaser", "rupert.lechner@seiler.de"],
    ["GER", "Altmann", "cjost@pape.com"],
    ["GER", "Voigt", "leo87@jung.de"],
    ["GER", "Henning", "franzjosef64@krug.org"],
    ["GER", "Moritz", "mirko.greiner@weis.de"],
    ["GER", "Ludwig", "friedrich.beier@rau.org"],
    ["GER", "Hermann Seifert & Co.", "wilma11@schreiner.net"],
    ["GER", "Naumann", "engelbert53@schenk.com"],
    ["GER", "Schlegel & Co.", "voigt.eugen@hein.com"],
    ["GER", "Fuchs", "viola89@steffen.de"],
    ["GER", "Schüler", "hofmann.josip@blank.de"],
    ["GER", "Stadler Zeller", "ludmila.stein@schroter.org"],
    ["GER", "Keller", "adam.veit@hummel.com"],
    ["GER", "Jacobs", "diethard16@henke.de"],
    ["GER", "Nagel Geiger", "helmut34@heinemann.de"],
    ["GER", "Lang Petersen & Co.", "wlang@rothe.net"],
    ["GER", "Barthel Brinkmann", "ingeborg.jansen@jakob.org"],
    ["GER", "Haupt", "emilia.baumann@karl.de"],
    ["GER", "Hartung", "clindemann@bottcher.org"],
    ["GER", "Müller", "heinzwerner37@westphal.de"],
    ["GER", "Busse Born", "ohaag@ullrich.com"],
    ["GER", "Schäfer", "soren.stadler@eberhardt.de"],
    ["GER", "Reimann", "heinze.ingelore@martens.org"],
    ["GER", "Barth", "svenja.esser@moser.de"],
    ["GER", "Gärtner", "maier.milan@pohl.com"],
    ["GER", "Wimmer", "bartels.antonio@wiese.com"],
    ["GER", "Scheffler", "hedwig95@wolf.net"],
    ["GER", "Blum", "kramer.evamaria@niemann.com"],
    ["GER", "Bernhardt Straub & Co.", "pauline91@noack.net"],
    ["GER", "Werner", "cbeer@erdmann.de"],
    ["GER", "Baum Greiner & Co.", "guido.breuer@wunderlich.net"],
    ["GER", "Geiger", "bsturm@gunther.com"],
    ["GER", "Bachmann", "nina21@john.de"],
    ["GER", "Bär Ludwig", "kaiser.simon@herrmann.de"],
    ["GER", "Heinze Brunner", "mdorn@wilke.com"],
    ["GER", "Bode e.V.", "ahauser@petersen.com"],
    ["GER", "Freund", "astrid.kiefer@herrmann.org"],
    ["GER", "Glaser", "jenny.merkel@weis.org"],
    ["GER", "Oswald", "milan08@schramm.com"],
    ["GER", "Gärtner", "jkiefer@michels.de"],
    ["GER", "Sauter", "simon.hartmann@freitag.de"],
    ["GER", "Bach", "karla.rupp@neumann.de"],
    ["GER", "Wieland", "egeyer@meister.de"],
    ["GER", "Jürgens", "konstanze.volker@bruckner.com"],
    ["GER", "Schwab Maier", "sonntag.rosmarie@brandl.com"],
    ["GER", "Kaufmann", "hanspeter.krauss@geisler.de"],
    ["GER", "Philipp Knoll Stiftung & Co.", "wnoll@wegener.org"],
    ["GER", "Becker Stiftung & Co.", "sylvia02@ehlers.com"],
    ["GER", "Noll Neubert Stiftung & Co.", "schmitt.ortwin@gerber.net"],
    ["GER", "Buck", "anne.hentschel@heinze.de"],
    ["GER", "Petersen", "doring.madeleine@brunner.de"],
    ["GER", "Barth", "lorenz.winkler@buchholz.org"],
    ["GER", "Fischer Braun", "liesel.schramm@binder.de"],
    ["GER", "Roth", "adam.evamaria@schweizer.de"],
    ["GER", "Arnold Ahrens", "kbecker@herzog.com"],
    ["GER", "Müller", "franzjosef85@pfeiffer.net"],
    ["GER", "Siebert e.V.", "reichel.judith@gruber.com"],
    ["GER", "Hein Wolf", "denis.moller@sommer.com"],
    ["GER", "Kaufmann Schäfer", "irmgard.philipp@schilling.de"],
    ["GER", "100", "Geiger Preuß & Co.", "brand.alois@dittrich.de"],
    ["FRA", "Brun Bruneau", "martin.bertin@reynaud.fr"],
    ["FRA", "Leduc Roche", "oroche@laine.com"],
    ["FRA", "Albert", "guy44@dasilva.fr"],
    ["FRA", "Lecoq Lefort", "anais06@carpentier.fr"],
    ["FRA", "Renard Guillou", "ptorres@tanguy.fr"],
    ["FRA", "Petit", "therese47@louis.com"],
    ["FRA", "Blanc", "ggrondin@becker.fr"],
    ["FRA", "Briand", "gmartinez@carpentier.com"],
    ["FRA", "Diaz Wagner", "pierre.sauvage@dossantos.net"],
    ["FRA", "Lenoir", "gdurand@bonneau.com"],
    ["FRA", "Colin", "xdelattre@leblanc.fr"],
    ["FRA", "Mahe", "vbesson@faure.fr"],
    ["FRA", "Chevalier Petit et Fils", "marc65@hoarau.org"],
    ["FRA", "Albert Lebrun.", "gperrin@teixeira.net"],
    ["FRA", "Pottier Grondin et Fils", "nicolas.rocher@diallo.fr"],
    ["FRA", "Muller Picard", "vauger@auger.fr"],
    ["FRA", "Robin", "hebert.aurelie@gimenez.fr"],
    ["FRA", "Baron", "mallet.antoine@bruneau.fr"],
    ["FRA", "Blot", "yves.jacques@riviere.com"],
    ["FRA", "Goncalves", "bigot.arnaude@riou.fr"],
    ["FRA", "Cohen Petitjean et Fils", "joseph72@delannoy.org"],
    ["FRA", "Fournier", "jeanne.faivre@navarro.com"],
    ["FRA", "Bonnin Andre", "fabre.martin@gomez.com"],
    ["FRA", "Pires", "francoise29@delannoy.com"],
    ["FRA", "Neveu.", "ledoux.emmanuel@meyer.fr"],
    ["FRA", "Goncalves", "dleleu@leclercq.fr"],
    ["FRA", "Petitjean", "lucas24@peltier.com"],
    ["FRA", "Turpin De Sousa", "roux.laure@guillet.com"],
    ["FRA", "Delaunay", "penelope.courtois@collet.net"],
    ["FRA", "Neveu", "brigitte60@bertin.com"],
    ["FRA", "Bouvier Blanchet.", "rmonnier@remy.com"],
    ["FRA", "Lecoq", "josette05@clement.com"],
    ["FRA", "Moreau Martineau", "vincent48@boyer.fr"],
    ["FRA", "Bonnin", "nicolas85@duval.net"],
    ["FRA", "Blondel", "alexandre.texier@guichard.org"],
    ["FRA", "Monnier", "ibousquet@pages.com"],
    ["FRA", "De Sousa Maurice et Fils", "smartinez@menard.fr"],
    ["FRA", "Bousquet", "ruiz.maurice@pasquier.com"],
    ["FRA", "Peron", "tessier.denis@dupre.com"],
    ["FRA", "Voisin", "schmitt.emmanuelle@philippe.com"],
    ["FRA", "Lefebvre", "pdelorme@lefort.net"],
    ["FRA", "Parent.", "adam.hortense@alves.org"],
    ["FRA", "Lefebvre", "juliette.francois@labbe.fr"],
    ["FRA", "Berger", "corinne08@marechal.fr"],
    ["FRA", "Weiss et Fils", "pmaillard@roussel.fr"],
    ["FRA", "Rossi", "esanchez@michaud.net"],
    ["FRA", "Maurice", "odette34@guillou.net"],
    ["FRA", "Maury", "hoareau.eric@riviere.fr"],
    ["FRA", "Lombard Moreau.", "krenard@hoarau.com"],
    ["FRA", "Boucher", "carpentier.ines@legall.fr"],
    ["FRA", "Lopez Robin.", "pereira.victor@riou.com"],
    ["FRA", "Grondin", "marie02@leroux.net"],
    ["FRA", "Garcia", "eandre@barthelemy.com"],
    ["FRA", "Gilbert", "gomes.remy@pages.com"],
    ["FRA", "Louis", "ubernard@lecoq.com"],
    ["FRA", "Legros", "astrid34@blanchet.com"],
    ["FRA", "Gilles.", "ybousquet@duval.fr"],
    ["FRA", "Moulin", "therese77@bonneau.fr"],
    ["FRA", "Costa", "ddesousa@hubert.org"],
    ["FRA", "Lopes", "lchevallier@pelletier.fr"],
    ["FRA", "Perrier", "celine35@levy.net"],
    ["FRA", "Gonzalez Paris et Fils", "qmercier@pottier.com"],
    ["FRA", "Gallet Lopes", "yves69@langlois.net"],
    ["FRA", "Gilles", "victoire.martins@girard.fr"],
    ["FRA", "Bertin", "william.dias@charrier.fr"],
    ["FRA", "Riou Leclercq", "fcarpentier@robert.com"],
    ["FRA", "Pasquier Durand", "oceane.prevost@arnaud.net"],
    ["FRA", "Menard", "ocoste@charles.com"],
    ["FRA", "Francois", "rlaine@garnier.fr"],
    ["FRA", "Benoit", "wchauvet@regnier.com"],
    ["FRA", "Gerard", "henriette.dijoux@hardy.com"],
    ["FRA", "Parent", "tboutin@nguyen.fr"],
    ["FRA", "Lacombe", "jerome.gaillard@dumont.fr"],
    ["FRA", "Merle", "cmarechal@clement.fr"],
    ["FRA", "Delannoy", "anouk35@coulon.com"],
    ["FRA", "Valentin", "jules.collin@legros.net"],
    ["FRA", "Wagner", "dijoux.susanne@lejeune.fr"],
    ["FRA", "Seguin", "laine.antoine@dupont.net"],
    ["FRA", "Gauthier", "tbarbier@pineau.fr"],
    ["FRA", "Brun", "guillon.brigitte@bodin.net"],
    ["FRA", "Allard.", "elise.becker@jacques.fr"],
    ["FRA", "Jacquot", "henriette38@collet.net"],
    ["FRA", "Munoz", "lucy.meunier@dumont.com"],
    ["FRA", "Delannoy", "perez.olivier@ferreira.fr"],
    ["FRA", "Leclercq", "vbousquet@leroux.fr"],
    ["FRA", "Dupuis", "alix.langlois@voisin.com"],
    ["FRA", "Lejeune", "antoine.perret@leveque.org"],
    ["FRA", "Guillon", "wschneider@dumas.fr"],
    ["FRA", "Blanc Moulin", "gaillard.rene@gros.com"],
    ["FRA", "Godard", "richard.salmon@techer.fr"],
    ["FRA", "Aubry", "laurent.dossantos@marie.fr"],
    ["FRA", "Duhamel", "thomas81@boulanger.org"],
    ["FRA", "Traore", "guillot.benjamin@delorme.com"],
    ["FRA", "Boucher", "dupuis.susan@huet.fr"],
    ["FRA", "Tanguy", "maury.isaac@maurice.org"],
    ["FRA", "Le Gall", "arnaude89@morel.fr"],
    ["FRA", "Bernard", "antoine.faure@meyer.com"],
    ["FRA", "Olivier", "adrien.roux@techer.com"],
    ["FRA", "Benoit", "adele.legendre@royer.com"],
    ["FRA", "Gallet", "henry.joseph@valentin.net"],
    ["SWE", "Gunvor Mattsson", "berggren.reinhold@bjorklund.com"],
    ["SWE", "Forsberg & Holm", "ossian.olofsson@lundstrom.com"],
    ["SWE", "Blomqvist", "alice58@eklund.com"],
    ["SWE", "Lindgren & Jakobsson", "qandreasson@sjoberg.com"],
    ["SWE", "Jansson", "cberg@hansen.net"],
    ["SWE", "Isaksson & Axelsson", "simon86@lund.com"],
    ["SWE", "Olofsson", "nordin.martina@sjogren.biz"],
    ["SWE", "Jonny Persson", "erling.martensson@arvidsson.com"],
    ["SWE", "Åström och Öberg", "linne.holmqvist@sjoberg.com"],
    ["SWE", "Syster Sjöberg", "annette09@lind.com"],
    ["SWE", "Jonsson & Lundgren", "blom.olga@sundstrom.com"],
    ["SWE", "Danielsson", "elfrida.oberg@jonasson.info"],
    ["SWE", "Sverker Holmgren", "tord.nordstrom@sundberg.com"],
    ["SWE", "Sundberg och Nordström", "leila.dahlberg@olsson.com"],
    ["SWE", "Lundström och Blomqvist", "adrian58@nyberg.com"],
    ["SWE", "Wallin och Falk", "xastrom@hakansson.biz"],
    ["SWE", "Nyberg och Björk", "rsjoberg@claesson.com"],
    ["SWE", "Berggren & Viklund", "fritjof.nordstrom@gustafsson.com"],
    ["SWE", "Samuelsson", "solvig99@blom.com"],
    ["SWE", "Åberg", "hhenriksson@viklund.com"],
    ["SWE", "Berggren", "orjan34@axelsson.com"],
    ["SWE", "Sundström & Fransson", "nyberg.torsten@sundqvist.org"],
    ["SWE", "Persson och Andersson", "vendela.andersson@stromberg.com"],
    ["SWE", "Hedlund och Nyström", "werner70@sundberg.biz"],
    ["SWE", "Åberg", "holmfrid48@hermansson.com"],
    ["SWE", "Lindström", "evert.holmberg@andreasson.com"],
    ["SWE", "Hermansson", "sjogren.marianne@jakobsson.info"],
    ["SWE", "Nyberg & Forsberg", "edmund49@bjorklund.com"],
    ["SWE", "Lundgren och Söderberg", "leonard.eklund@blom.info"],
    ["SWE", "Ström & Pettersson", "ola.hansen@eriksson.com"],
    ["SWE", "Björklund och Åkesson", "thenriksson@holmqvist.com"],
    ["SWE", "Frida Gunnarsson", "bergman.kristin@sjoberg.com"],
    ["SWE", "Holm & Blom", "lisbeth.andreasson@sjoberg.biz"],
    ["SWE", "Sjöberg och Sundström", "sverker34@henriksson.org"],
    ["SWE", "Henriksson", "reino.hansson@larsson.com"],
    ["SWE", "Åström & Berg", "larsake.bjork@jonsson.com"],
    ["SWE", "Arvidsson", "theresia95@abrahamsson.com"],
    ["SWE", "Ivarsson", "ronnie.sjogren@nystrom.com"],
    ["SWE", "Ivarsson", "crister21@lofgren.com"],
    ["SWE", "Nilsson och Lundgren", "paulina.andersson@lundstrom.info"],
    ["SWE", "Svensson och Isaksson", "olov.jakobsson@stromberg.com"],
    ["SWE", "Odd Sandström", "aolsson@bergstrom.com"],
    ["SWE", "Viveka Hedlund", "lindberg.elvira@akesson.com"],
    ["SWE", "Claesson & Sandström", "zdanielsson@henriksson.com"],
    ["SWE", "Bergman & Nilsson", "synnove.aberg@wallin.com"],
    ["SWE", "Lydia Persson", "frida.gustafsson@mattsson.com"],
    ["SWE", "Nanna Månsson", "fransson.josef@ekstrom.biz"],
    ["SWE", "Martinsson & Lindberg", "catharina91@arvidsson.net"],
    ["SWE", "Leander Holmgren", "lundberg.martin@berggren.info"],
    ["SWE", "Gustafsson och Wallin", "rosita82@mansson.com"],
    ["SWE", "Pettersson", "xjonasson@bjorklund.com"],
    ["SWE", "Holmgren & Holm", "fredriksson.ralf@strom.org"],
    ["SWE", "Ek och Sandberg", "mariana68@gunnarsson.com"],
    ["SWE", "Tom Hermansson", "solve24@nyberg.info"],
    ["SWE", "Nordström", "ludvig.larsson@isaksson.com"],
    ["SWE", "Olsson", "gunda.engstrom@forsberg.com"],
    ["SWE", "Carl Holm", "clindstrom@lind.com"],
    ["SWE", "Hellström", "norberg.louis@nilsson.net"],
    ["SWE", "Magnusson och Wallin", "hermansson.rosita@norberg.com"],
    ["SWE", "Lundin", "gerhard.bergqvist@abrahamsson.biz"],
    ["SWE", "Blomqvist", "jeanette.larsson@nordin.com"],
    ["SWE", "Wallin", "gota.sandstrom@hermansson.com"],
    ["SWE", "Mårtensson & Mårtensson", "seved.hansen@hansson.info"],
    ["SWE", "Paul Eliasson", "sebastian38@mansson.com"],
    ["SWE", "Eliasson & Viklund", "wek@jansson.com"],
    ["SWE", "Bergström", "william20@olofsson.net"],
    ["SWE", "Lundström", "divarsson@fredriksson.com"],
    ["SWE", "Mårtensson", "yastrom@hellstrom.info"],
    ["SWE", "Ek & Berg", "kristina95@eklund.com"],
    ["SWE", "Anna-Carin Lindgren", "hulda.sjogren@danielsson.info"],
    ["SWE", "Lindgren", "blom.adam@ek.com"],
    ["SWE", "Fredriksson och Danielsson", "hansen.natanael@lindstrom.net"],
    ["SWE", "Malte Sundström", "solsson@sjogren.com"],
    ["SWE", "Sandström och Henriksson", "vivian58@sundberg.com"],
    ["SWE", "Holmqvist", "vilhelmina41@nyberg.com"],
    ["SWE", "Olsson & Magnusson", "aakesson@jonsson.net"],
    ["SWE", "Blom", "olofsson.sonja@martensson.com"],
    ["SWE", "Magnusson", "marit.jonsson@berg.com"],
    ["SWE", "Fredriksson och Sundqvist", "fjohansson@pettersson.com"],
    ["SWE", "Mattsson & Blom", "frideborg.nystrom@olofsson.info"],
    ["SWE", "Öberg", "marita.holmqvist@blomqvist.com"],
    ["SWE", "Lundström och Lundberg", "brita27@nystrom.com"],
    ["SWE", "Forsberg", "sundstrom.larseric@nystrom.com"],
    ["SWE", "Marita Hermansson", "sblom@eriksson.com"],
    ["SWE", "Åkesson och Lundgren", "lundstrom.theodor@sandstrom.net"],
    ["SWE", "Wallin", "oskar07@claesson.info"],
    ["SWE", "Jonasson & Mattsson", "micael.falk@jonasson.com"],
    ["SWE", "Pettersson & Bergström", "mansson.margareta@eliasson.com"],
    ["SWE", "Nyberg & Björklund", "inez27@blom.com"],
    ["SWE", "Eliasson och Lundqvist", "lindqvist.svea@andersson.net"],
    ["SWE", "Abrahamsson", "iaxelsson@wallin.org"],
    ["SWE", "Jonasson & Claesson", "martha.lund@hellstrom.com"],
    ["SWE", "Gustafsson", "lindberg.ingabritt@holm.com"],
    ["SWE", "Isaksson och Sandström", "alrik.hermansson@sandberg.com"],
    ["SWE", "Helfrid Berggren", "jsandberg@bergstrom.com"],
    ["SWE", "Norberg och Sundberg", "lindstrom.sverker@sjoberg.com"],
    ["SWE", "Nyberg", "lydia.isaksson@mansson.info"],
    ["SWE", "Jansson och Abrahamsson", "pengstrom@eliasson.biz"],
    ["SWE", "Nyström och Eklund", "arne45@axelsson.com"],
    ["SWE", "Blenda Lindström", "cholmqvist@palsson.info"],
    ["BRA", "Soto", "mbrito@casanova.com"],
    ["BRA", "Salgado-Rosa", "tvieira@corona.net.br"],
    ["BRA", "Ferminiano Comercial", "jbarreto@verdara.com"],
    ["BRA", "Branco", "manuel.santiago@dias.net"],
    ["BRA", "Pena-Duarte", "daniela28@grego.br"],
    ["BRA", "das Neves Comercial", "qserrano@burgos.br"],
    ["BRA", "Pontes-Sepúlveda", "xgalvao@bittencourt.net.br"],
    ["BRA", "Quintana e Teles e Associados", "bdasneves@galhardo.net.br"],
    ["BRA", "Pena-Corona", "faro.leonardo@sanches.br"],
    ["BRA", "Bonilha-Ferraz", "ddesouza@deoliveira.com"],
    ["BRA", "de Aguiar-Bittencourt", "gteles@serra.com"],
    ["BRA", "Solano-Azevedo", "thalissa26@ortega.com.br"],
    ["BRA", "Camacho e Associados", "fatima73@deaguiar.com"],
    ["BRA", "Maia e Santacruz", "escobar.giovane@galvao.org"],
    ["BRA", "Duarte-Vila", "jasmin.bezerra@brito.com"],
    ["BRA", "Pereira e Estrada", "scaldeira@uchoa.net.br"],
    ["BRA", "Caldeira e Associados", "neves.benjamin@ortega.net.br"],
    ["BRA", "Lira e Filhos", "sebastiao.delvalle@toledo.com.br"],
    ["BRA", "Rosa e D'ávila e Associados", "olivia.avila@camacho.net.br"],
    ["BRA", "Martines Comercial", "jbittencourt@benites.com.br"],
    ["BRA", "Esteves e Filhos", "paulina82@quintana.com.br"],
    ["BRA", "Velasques e Fernandes", "urias.suzana@serrano.com"],
    ["BRA", "Marin e Vasques", "sebastiao35@molina.org"],
    ["BRA", "da Silva Comercial", "constancia15@soto.com.br"],
    ["BRA", "Galhardo-Fontes", "bgrego@dominato.com"],
    ["BRA", "Balestero e Filhos", "rezende.alexandre@rocha.org"],
    ["BRA", "Franco Comercial", "nadia.bonilha@rivera.br"],
    ["BRA", "Mascarenhas e Filhos", "darosa.alma@saraiva.com"],
    ["BRA", "Cordeiro e Franco", "pmaldonado@delgado.net.br"],
    ["BRA", "Grego-Cervantes", "balestero.camilo@bezerra.org"],
    ["BRA", "Verdara e Santacruz", "abril.serrano@balestero.com.br"],
    ["BRA", "Grego", "bruno13@vieira.com"],
    ["BRA", "Queirós e Filhos", "colaco.helena@pereira.org"],
    ["BRA", "Brito e Toledo", "zreis@torres.com"],
    ["BRA", "Cervantes Comercial", "rodrigo.dominato@vasques.com"],
    ["BRA", "de Oliveira e Salgado", "wqueiros@ferreira.net"],
    ["BRA", "Estrada-Serna", "laura22@salazar.com"],
    ["BRA", "Tamoio e Fernandes", "jasmin.benites@sepulveda.com"],
    ["BRA", "Pacheco", "josue11@guerra.com.br"],
    ["BRA", "Salas e Casanova e Associados", "yferreira@barreto.org"],
    ["BRA", "de Souza-Fidalgo", "usepulveda@franco.com.br"],
    ["BRA", "Marinho Comercial", "rcorona@bonilha.com"],
    ["BRA", "Mendes Comercial", "ycolaco@cervantes.org"],
    ["BRA", "de Souza e Branco", "madeira.joana@corona.com"],
    ["BRA", "D'ávila-Aguiar", "marques.david@batista.com.br"],
    ["BRA", "Marinho-Valência", "vila.ashley@franco.net.br"],
    ["BRA", "Queirós e Vila", "tcervantes@mares.com"],
    ["BRA", "Padilha e Matias", "qzambrano@rocha.com"],
    ["BRA", "Valência e Valência", "zlozano@solano.net.br"],
    ["BRA", "Salazar e Neves", "andrea.queiros@burgos.com.br"],
    ["BRA", "Marinho Comercial", "xfeliciano@quintana.com.br"],
    ["BRA", "Bezerra e Gusmão", "gabriel56@ortiz.net.br"],
    ["BRA", "Burgos Comercial", "josefina.estrada@valdez.com"],
    ["BRA", "Delatorre", "jimenes.estevao@valentin.net.br"],
    ["BRA", "de Aguiar Comercial", "thales.padilha@garcia.com.br"],
    ["BRA", "Serna e Escobar", "lneves@verdugo.net"],
    ["BRA", "Benites-Mendonça", "valentin.urias@cordeiro.com"],
    ["BRA", "Montenegro-Ramires", "valeria51@davila.net"],
    ["BRA", "Neves-Valência", "domingues.mariana@campos.org"],
    ["BRA", "Barreto e Filhos", "jdelatorre@lovato.org"],
    ["BRA", "Fonseca-Matos", "mcorreia@quintana.com"],
    ["BRA", "Fonseca", "constancia.delvalle@vega.net"],
    ["BRA", "Rangel e Rodrigues", "jrico@abreu.com"],
    ["BRA", "Bonilha Comercial", "hernani46@matias.br"],
    ["BRA", "Escobar e Fontes", "pvaldez@vila.com"],
    ["BRA", "Padrão e Associados", "kpacheco@rivera.com.br"],
    ["BRA", "Paes e Salgado", "rafael.zaragoca@queiros.net"],
    ["BRA", "Gomes e Ramires e Filhos", "martinho62@valencia.net.br"],
    ["BRA", "Fernandes e Filhos", "jduarte@darosa.com.br"],
    ["BRA", "Faria e Colaço", "everton29@bonilha.com"],
    ["BRA", "Rico Comercial", "avila.hugo@corona.com.br"],
    ["BRA", "Fontes e Lira e Filhos", "christopher.mendonca@valencia.net.br"],
    ["BRA", "Gomes-de Oliveira", "matos.martinho@mendonca.com"],
    ["BRA", "Pacheco-Teles", "ortega.everton@beltrao.com"],
    ["BRA", "Padilha e Filhos", "horacio33@vasques.com.br"],
    ["BRA", "Ferminiano-Meireles", "alexandre.pontes@maldonado.net.br"],
    ["BRA", "Quintana e Padrão", "andrea.flores@dasdores.com.br"],
    ["BRA", "Domingues e Pereira", "aromero@perez.com"],
    ["BRA", "Bonilha Comercial", "andres.matos@maia.br"],
    ["BRA", "Chaves Comercial", "alan54@beltrao.org"],
    ["BRA", "Delvalle e Rangel", "giovane07@davila.net"],
    ["BRA", "de Oliveira e Associados", "madeira.demian@fontes.com.br"],
    ["BRA", "Rivera e da Silva", "serrano.ashley@ortega.com.br"],
    ["BRA", "Toledo e Paz", "catarina28@batista.com.br"],
    ["BRA", "Vieira e Neves", "lucas.rivera@pena.net.br"],
    ["BRA", "Velasques-Bonilha", "escobar.luciano@ferreira.com.br"],
    ["BRA", "Padilha e Meireles e Associados", "rocha.alessandra@escobar.com.br"],
    ["BRA", "Quintana e Bittencourt", "assuncao.valeria@jimenes.net"],
    ["BRA", "Zambrano-Lutero", "mendonca.rodrigo@ferreira.br"],
    ["BRA", "Rico Comercial", "isabella84@leon.br"],
    ["BRA", "Benites e Urias", "maite96@medina.net.br"],
    ["BRA", "de Aguiar-Fonseca", "isabella.gil@soares.org"],
    ["BRA", "Galvão e Ortiz", "chaves.mario@montenegro.com.br"],
    ["BRA", "Fontes e Verdugo", "bruno.flores@maia.com.br"],
    ["BRA", "Garcia e Rocha", "agustina.medina@montenegro.com.br"],
    ["BRA", "Serrano e Neves", "valeria84@beltrao.com"],
    ["BRA", "Pontes e Teles", "cervantes.benjamin@batista.br"],
    ["BRA", "Esteves-Mascarenhas", "salas.isadora@marin.net.br"],
    ["BRA", "Uchoa e Vale e Associados", "mascarenhas.felipe@jimenes.com.br"],
    ["BRA", "Queirós Comercial", "ariana56@marinho.net"],
)
